### ISSUE TITLE
Newline is not taking into account

### ISSUE THREAD

**Issue by chandrad** [rasbt/watermark#23]
Generally, programmer may use more than one library packages to be listed. 

```
%watermark -a "author" -d -t -v -m -p numpy,pandas,scipy,sklearn,statsmodels,matplotlib,seaborn,bokeh,xgboost,`\n
h2o,pymc3,lifelines,theano,altair

```
Any scope of including this functionality?

**Comment by rasbt** [comment]
Hi, Chandra,
I think the newline escape sequence `\n` doesn't work in this case since the is not typed as a string (i.e., without the quotation marks). However, a simple continuation char (backslash) should work! 

![screen shot 2016-12-13 at 11 39 03 am](https://cloud.githubusercontent.com/assets/5618407/21149464/8f5dcd2c-c129-11e6-9213-5e8f70e32c63.png)

It should maybe be clarified in the docs/Readme somewhere. If you want to send an PR, I would really appreciate it

**Comment by chandrad** [comment]
Simple backslash will do. Thanks for clarifying.
